// TYPES BLOGS
export const FETCH_BLOG_REQUEST = "FETCH_BLOG_REQUEST";
export const FETCH_BLOG_SUCCEEDED = "FETCH_BLOG_SUCCEEDED";
export const FETCH_BLOG_FAILED = "FETCH_BLOG_FAILED";

export const LIKE_BLOG_REQUEST = "LIKE_BLOG_REQUEST";
export const LIKE_BLOG_SUCCEEDED = "LIKE_BLOG_SUCCEEDED";
export const LIKE_BLOG_FAILED = "LIKE_BLOG_FAILED";

export const UNLIKE_BLOG_REQUEST = "UNLIKE_BLOG_REQUEST";
export const UNLIKE_BLOG_SUCCEEDED = "UNLIKE_BLOG_SUCCEEDED";
export const UNLIKE_BLOG_FAILED = "UNLIKE_BLOG_FAILED";

export const DELETE_BLOG_REQUEST = "DELETE_BLOG_REQUEST";
export const DELETE_BLOG_SUCCEEDED = "DELETE_BLOG_SUCCEEDED";
export const DELETE_BLOG_FAILED = "DELETE_BLOG_FAILED";

export const ADD_BLOG_REQUEST = "ADD_BLOG_REQUEST";
export const ADD_BLOG_SUCCEEDED = "ADD_BLOG_SUCCEEDED";
export const ADD_BLOG_FAILED = "ADD_BLOG_FAILED";

export const GET_BLOG_DETAIL_REQUEST = "GET_BLOG_DETAIL_REQUEST";
export const GET_BLOG_DETAIL_SUCCEEDED = "GET_BLOG_DETAIL_SUCCEEDED";
export const GET_BLOG_DETAIL_FAILED = "GET_BLOG_DETAIL_FAILED";

export const SUBMIT_COMMENT_BLOG_REQUEST = "SUBMIT_COMMENT_BLOG_REQUEST";
export const SUBMIT_COMMENT_BLOG_SUCCEEDED = "SUBMIT_COMMENT_BLOG_SUCCEEDED";
export const SUBMIT_COMMENT_BLOG_FAILED = "SUBMIT_COMMENT_BLOG_FAILED";

export const LOADING_BLOG_PROCESSING = "LOADING_BLOG_PROCESSING";
export const LOADING_BLOG_PROCESSED = "LOADING_BLOG_PROCESSED";

export const CLEAR_ERROR = "CLEAR_ERROR";

export const OPEN_BLOG_MODAL = "OPEN_BLOG_MODAL";
export const CLOSE_BLOG_MODAL = "CLOSE_BLOG_MODAL";

export const LOADING_MODAL_PROCESSING = "LOADING_MODAL_PROCESSING";
export const LOADING_MODAL_PROCESSED = "LOADING_MODAL_PROCESSED";

// TYPES AUTH
export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCEEDED = "LOGIN_USER_SUCCEEDED";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";

export const SIGN_UP_USER_REQUEST = "SIGN_UP_USER_REQUEST";
export const SIGN_UP_USER_SUCCEEDED = "SIGN_UP_USER_SUCCEEDED";
export const SIGN_UP_USER_FAILED = "SIGN_UP_USER_FAILED";

export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";
export const LOGOUT_USER_SUCCEEDED = "LOGOUT_USER_SUCCEEDED";
export const LOGOUT_USER_FAILED = "LOGOUT_USER_FAILED";

export const GET_USER_RESQUEST = "GET_USER_RESQUEST";
export const GET_USER_SUCCEEDED = "GET_USER_SUCCEEDED";
export const GET_USER_FAILED = "GET_USER_FAILED";

export const GET_USER_BY_USERHANDLE_RESQUEST = "GET_USER_BY_USERHANDLE_RESQUEST";
// export const GET_USER_BY_USERHANDLE_SUCCEEDED = "GET_USER_BY_USERHANDLE_SUCCEEDED";
// export const GET_USER_BY_USERHANDLE_FAILED = "GET_USER_BY_USERHANDLE_FAILED";

export const UPLOAD_USER_IMAGE_RESQUEST = "UPLOAD_USER_IMAGE_RESQUEST";

export const MARK_NOTIFICATION_READ_REQUEST = "MARK_NOTIFICATION_READ_REQUEST";
export const MARK_NOTIFICATION_READ_SUCCEEDED = "MARK_NOTIFICATION_READ_SUCCEEDED";
export const MARK_NOTIFICATION_READ_FAILED = "MARK_NOTIFICATION_READ_FAILED";

export const AUTH_PROCESSING = "AUTH_PROCESSING";
export const AUTH_PROCESSED = "AUTH_PROCESSED";

export const AUTHENTICATED_REQUEST = "AUTHENTICATED_REQUEST";
export const AUTHENTICATED_SUCCEEDED = "AUTHENTICATED_SUCCEEDED";
export const AUTHENTICATED_FAILED = "AUTHENTICATED_FAILED";

export const EDIT_USER_REQUEST = "EDIT_USER_REQUEST";
export const EDIT_USER_FAILED = "EDIT_USER_FAILED";

export const LOADING_PROCESSING = "LOADING_PROCESSING";
export const LOADING_PROCESSED = "LOADING_PROCESSED";

export const OPEN_USER_MODAL = "OPEN_USER_MODAL";
export const CLOSE_USER_MODAL = "CLOSE_USER_MODAL";
